// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513000000_ExtendMatchToFourPlayersWithPlacement")]
    partial class ExtendMatchToFourPlayersWithPlacement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShorthandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Domain.Competition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BestOf")
                        .HasColumnType("int");

                    b.Property<string>("CompetitionType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasDiscriminator<string>("CompetitionType").HasValue("Competition");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.CompetitionMember", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompetitionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int?>("Seed")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CompetitionId");

                    b.HasIndex("CompetitionId");

                    b.ToTable("CompetitionMembers");
                });

            modelBuilder.Entity("Domain.Match", b =>
                {
                    b.Property<string>("CompetitionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BracketNumber")
                        .HasColumnType("int");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("FourthPlaceUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerCount")
                        .HasDefaultValue(2)
                        .HasColumnType("int");

                    b.Property<string>("PlayerFourUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerOneUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerThreeUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerTwoUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RegisteredTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondPlaceUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPlaceUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WinnerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompetitionId", "BracketNumber", "MatchNumber");

                    b.HasIndex("PlayerFourUserId", "CompetitionId");

                    b.HasIndex("PlayerOneUserId", "CompetitionId");

                    b.HasIndex("PlayerThreeUserId", "CompetitionId");

                    b.HasIndex("PlayerTwoUserId", "CompetitionId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Domain.Round", b =>
                {
                    b.Property<string>("CompetitionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BracketNumber")
                        .HasColumnType("int");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("PlayerFourCharacterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerOneCharacterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerThreeCharacterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlayerTwoCharacterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WinnerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompetitionId", "BracketNumber", "MatchNumber", "RoundNumber");

                    b.HasIndex("PlayerFourCharacterId");

                    b.HasIndex("PlayerOneCharacterId");

                    b.HasIndex("PlayerThreeCharacterId");

                    b.HasIndex("PlayerTwoCharacterId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Casual", b =>
                {
                    b.HasBaseType("Domain.Competition");

                    b.HasDiscriminator().HasValue("Casual");
                });

            modelBuilder.Entity("Domain.League", b =>
                {
                    b.HasBaseType("Domain.Competition");

                    b.Property<int?>("PlayerCount")
                        .HasColumnName("LeaguePlayerCount")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("League");
                });

            modelBuilder.Entity("Domain.Tournament", b =>
                {
                    b.HasBaseType("Domain.Competition");

                    b.Property<int>("BracketSize")
                        .HasColumnName("BracketSize")
                        .HasColumnType("int");

                    b.Property<string>("WinnerUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Tournament");
                });

            modelBuilder.Entity("Domain.CompetitionMember", b =>
                {
                    b.HasOne("Domain.Competition", "Competition")
                        .WithMany("Members")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("CompetitionMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Match", b =>
                {
                    b.HasOne("Domain.Competition", "Competition")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.CompetitionMember", "PlayerOne")
                        .WithMany("MatchesAsPlayerOne")
                        .HasForeignKey("PlayerOneUserId", "CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.CompetitionMember", "PlayerTwo")
                        .WithMany("MatchesAsPlayerTwo")
                        .HasForeignKey("PlayerTwoUserId", "CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.CompetitionMember", "PlayerThree")
                        .WithMany("MatchesAsPlayerThree")
                        .HasForeignKey("PlayerThreeUserId", "CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.CompetitionMember", "PlayerFour")
                        .WithMany("MatchesAsPlayerFour")
                        .HasForeignKey("PlayerFourUserId", "CompetitionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Competition");

                    b.Navigation("PlayerFour");

                    b.Navigation("PlayerOne");

                    b.Navigation("PlayerThree");

                    b.Navigation("PlayerTwo");
                });

            modelBuilder.Entity("Domain.Round", b =>
                {
                    b.HasOne("Domain.Character", "PlayerFourCharacter")
                        .WithMany("RoundsAsPlayerFour")
                        .HasForeignKey("PlayerFourCharacterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Character", "PlayerOneCharacter")
                        .WithMany("RoundsAsPlayerOne")
                        .HasForeignKey("PlayerOneCharacterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Character", "PlayerThreeCharacter")
                        .WithMany("RoundsAsPlayerThree")
                        .HasForeignKey("PlayerThreeCharacterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Character", "PlayerTwoCharacter")
                        .WithMany("RoundsAsPlayerTwo")
                        .HasForeignKey("PlayerTwoCharacterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Match", "Match")
                        .WithMany("Rounds")
                        .HasForeignKey("CompetitionId", "BracketNumber", "MatchNumber")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("PlayerFourCharacter");

                    b.Navigation("PlayerOneCharacter");

                    b.Navigation("PlayerThreeCharacter");

                    b.Navigation("PlayerTwoCharacter");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Character", b =>
                {
                    b.Navigation("RoundsAsPlayerFour");

                    b.Navigation("RoundsAsPlayerOne");

                    b.Navigation("RoundsAsPlayerThree");

                    b.Navigation("RoundsAsPlayerTwo");
                });

            modelBuilder.Entity("Domain.Competition", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Domain.CompetitionMember", b =>
                {
                    b.Navigation("MatchesAsPlayerFour");

                    b.Navigation("MatchesAsPlayerOne");

                    b.Navigation("MatchesAsPlayerThree");

                    b.Navigation("MatchesAsPlayerTwo");
                });

            modelBuilder.Entity("Domain.Match", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("CompetitionMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
